### PR TITLE
Fix https://github.com/brave/brave-browser/issues/4419

### PR DESCRIPTION
**Pull request by ryanbr**
Made generic to cover companies using custom domains.

Should fix the issue reported in https://github.com/brave/brave-browser/issues/4419

### CODE REVIEW

**Comment by fmarier** [comment]
It seems a little excessive to whitelist that domain on all pages. I'm trying to find a tighter rule.

**Comment by ryanbr** [comment]
> It seems a little excessive to whitelist that domain on all pages. I'm trying to find a tighter rule.

               ` "https://*.atlassian.net/secure/*"`

Maybe?

#edit. Maybe not,

**Comment by fmarier** [comment]
I'm hoping we don't have to whitelist it globally, so something like (doesn't work yet):
```
        {
            "https://*.atlassian.com/*": [
                "https://*.atlassian.net/*"
            ]
        },
        {
            "https://*.jira.com/*": [
                "https://*.atlassian.net/*"
            ]
        }
```

**Comment by fmarier** [comment]
That said, I can confirm that the global whitelisting works, so it's definitely a missing referrer on `atlassian.net` that's causing this pain

**Comment by ryanbr** [comment]
The main issue possibly would be companies uising atlassian services, but with there own domains. why chose the global whitelist, ofcourse if there is a better solution

**Comment by fmarier** [comment]
I don't have write access to this repo yet so I can't edit issues/PRs, so I've had to put the tighter fix I found in a separate PR: https://github.com/brave/referrer-whitelist/pull/14

**Pull request closed without merging**
